services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: [ "poetry", "run", "fastapi", "run", "app/main.py", "--port", "8000" ]
    volumes:
      - .:/app

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "poetry", "run", "python", "-m", "unittest", "discover", "-s", "app/tests" ]
    depends_on:
      - app
    volumes:
      - .:/app
